### ISSUE TITLE
Partner feedback: Better support of Regional data story 

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#45]
(1) documents abour regional data file structure
(2) explanation on impacts of regional data selection (why it will wipe out the previous change, why it cannot be used in "use previous config" section

**Comment by MeWu-IDM** [comment]
explain this in the UI instead of doc, @BHagedorn-IDM to provide content

**Comment by BHagedorn-IDM** [comment]
When a user selects a region from the drop-down, please have the following text pop up, replacing what is currently there:

"Are you sure you want to proceed? When you select this region, the application will reload all data from the input file with the corresponding name. This will override any changes that you have made to the configuration (e.g., run years)."

When loading from a previous run, 

title the pop-up box: "Select previous run to reload assumptions from." 
text in the pop-up box: "When you reload from a previous run, the option to change the default region values is not available. If you would like to run a new region, please cancel and instead choose to run a new simulation." 

if possible, on the configuration page, hide the region drop-down entirely rather than greying it out and labeling "unavailable". This change is optional, though.

**Comment by MeWu-IDM** [comment]
fixed, also hide the region if it is not available
